networks:
  application:
    driver: bridge
  databases:
    driver: bridge

volumes:
  postgres_test:
    driver: local

services:

  postgres-core:
    image: postgres:15.6
    container_name: ${PG_CONTAINER}
    restart: no
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_test:/var/lib/postgresql/data
      # --- Utenti (Auth) ---
      - ${DDL_AUTH_HUB_LOCATION}/${PERSON_DDL_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/01_auth_ddl.sql
      - ${DUMP_AUTH_HUB_LOCATION}/${GROUP_DUMP_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/02_group_dump.sql
      - ${DUMP_AUTH_HUB_LOCATION}/${PERSON_DUMP_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/03_person_dump.sql
      # --- Piattaforma (Ala) ---
      - ${DDL_ALARION_LOCATION}/base.sql:${DB_POSTGRES_CONTAINER_LOCATION}/00_base.sql
      - ${DDL_ALARION_LOCATION}/${CORE_DDL_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/10_core_ddl.sql
      - ${DDL_ALARION_LOCATION}/${CAMPAIGN_DDL_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/11_campaign_ddl.sql
      - ${DDL_ALARION_LOCATION}/${CHARACTER_DDL_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/12_character_ddl.sql
      - ${DDL_ALARION_LOCATION}/${ATTENDACE_PS_DDL}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/13_attendance_ps_ddl.sql
      - ${DDL_ALARION_LOCATION}/${EFFECTS_DDL_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/14_effects_ddl.sql
      - ${DDL_ALARION_LOCATION}/${MANAGEMENT_DDL_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/15_management_ddl.sql
      - ${DUMP_ALARION_LOCATION}/${ABILITIES_DUMP_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/20_abilities_dump.sql
      - ${DUMP_ALARION_LOCATION}/${EFFECTS_DUMP_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/21_effects_dump.sql
      - ${DUMP_ALARION_LOCATION}/${NOTES_DUMP_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/22_notes_dump.sql
      - ${DUMP_ALARION_LOCATION}/${REALMS_DUMP_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/23_realms_dump.sql
      - ${DUMP_ALARION_LOCATION}/${ROADS_DUMP_NAME}.sql:${DB_POSTGRES_CONTAINER_LOCATION}/24_roads_dump.sql
    networks:
      - databases

  ############## Keycloak Test ##############
  keycloak_test: #/opt/keycloak/bin/kc.sh export --realm user-auth --users same_file --file /tmp/users_dump_TEST-01.json
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: ${KC_CONTAINER}
    restart: no
    environment:
      KC_HOSTNAME: ${HOST}
      KC_HOSTNAME_PORT: ${KC_EXTERNAL_PORT}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./services/keycloak/themes/:/opt/keycloak/themes/
      - ./services/keycloak/${PERSON_DUMP_NAME}.json:/opt/keycloak/data/import/${PERSON_DUMP_NAME}.json
    command: [ "start-dev", "--import-realm","--http-port=5443" ]
    ports:
      - '5443:5443'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/localhost/5443 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"
        ]
      interval: 5s
      timeout: 2s
      retries: 50
    networks:
      - application
