-- Ledger PS
CREATE TABLE IF NOT EXISTS card_transactions
(
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid         UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  card_id      BIGINT NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  source       card_tx_source_enum NOT NULL,
  amount       INTEGER NOT NULL,
  reference_id BIGINT NOT NULL, -- event_day_id
  note         TEXT,
  created_at   BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
  updated_at   BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
  is_active    BOOLEAN NOT NULL DEFAULT true
);

DROP TRIGGER IF EXISTS card_transactions_refresh_updated_at ON card_transactions;
CREATE TRIGGER card_transactions_refresh_updated_at
BEFORE UPDATE ON card_transactions
FOR EACH ROW EXECUTE FUNCTION refresh_updated_at();

-- Evita doppio +1 per stessa card e stessa giornata
CREATE UNIQUE INDEX IF NOT EXISTS ux_card_tx_event_day_unique
ON card_transactions(card_id, source, reference_id)
WHERE is_active = true AND source = 'event_day';


-- Attendance
CREATE TABLE IF NOT EXISTS character_attendance
(
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid         UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
  event_day_id BIGINT NOT NULL REFERENCES event_days(id) ON DELETE CASCADE,
  status       attendance_status_enum NOT NULL DEFAULT 'present',
  created_at   BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
  updated_at   BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
  is_active    BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT ux_character_day UNIQUE (character_id, event_day_id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_character_id ON character_attendance(character_id);
CREATE INDEX IF NOT EXISTS idx_attendance_event_day_id ON character_attendance(event_day_id);

DROP TRIGGER IF EXISTS character_attendance_refresh_updated_at ON character_attendance;
CREATE TRIGGER character_attendance_refresh_updated_at
BEFORE UPDATE ON character_attendance
FOR EACH ROW EXECUTE FUNCTION refresh_updated_at();


-- Trigger function: present => +1, absent => 0
CREATE OR REPLACE FUNCTION apply_ps_from_attendance()
RETURNS TRIGGER AS
$$
DECLARE
  v_card_id BIGINT;
  v_tx_id   BIGINT;
BEGIN
  IF NEW.is_active IS DISTINCT FROM true THEN
    RETURN NEW;
  END IF;

  SELECT c.card_id INTO v_card_id
  FROM characters c
  WHERE c.id = NEW.character_id;

  IF v_card_id IS NULL THEN
    RAISE EXCEPTION 'Character % has no card_id (cannot award PS)', NEW.character_id;
  END IF;

  -- INSERT
  IF TG_OP = 'INSERT' THEN
    IF NEW.status = 'present' THEN
      INSERT INTO card_transactions(card_id, source, amount, reference_id, note)
      VALUES (v_card_id, 'event_day', 1, NEW.event_day_id, 'PS +1: present')
      ON CONFLICT DO NOTHING;

      UPDATE cards
      SET total_points     = total_points + 1,
          available_points = available_points + 1
      WHERE id = v_card_id;
    END IF;
    RETURN NEW;
  END IF;

  -- UPDATE
  IF TG_OP = 'UPDATE' THEN
    -- absent -> present : +1
    IF (OLD.status IS DISTINCT FROM 'present') AND (NEW.status = 'present') THEN
      INSERT INTO card_transactions(card_id, source, amount, reference_id, note)
      VALUES (v_card_id, 'event_day', 1, NEW.event_day_id, 'PS +1: became present')
      ON CONFLICT DO NOTHING;

      UPDATE cards
      SET total_points     = total_points + 1,
          available_points = available_points + 1
      WHERE id = v_card_id;

      RETURN NEW;
    END IF;

    -- present -> absent : -1 (torna a 0)
    IF (OLD.status = 'present') AND (NEW.status IS DISTINCT FROM 'present') THEN
      SELECT id INTO v_tx_id
      FROM card_transactions
      WHERE card_id = v_card_id
        AND source = 'event_day'
        AND reference_id = NEW.event_day_id
        AND is_active = true
      ORDER BY id DESC
      LIMIT 1;

      IF v_tx_id IS NOT NULL THEN
        UPDATE card_transactions SET is_active = false WHERE id = v_tx_id;

        UPDATE cards
        SET total_points     = total_points - 1,
            available_points = available_points - 1
        WHERE id = v_card_id;
      END IF;

      RETURN NEW;
    END IF;

    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_apply_ps_from_attendance ON character_attendance;
CREATE TRIGGER trg_apply_ps_from_attendance
AFTER INSERT OR UPDATE OF status, is_active
ON character_attendance
FOR EACH ROW
EXECUTE FUNCTION apply_ps_from_attendance();
