-- 10_campaigns.sql

CREATE TABLE IF NOT EXISTS campaigns
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at  BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    updated_at  BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    is_active   BOOLEAN NOT NULL DEFAULT true
);

DROP TRIGGER IF EXISTS campaigns_refresh_updated_at ON campaigns;
CREATE TRIGGER campaigns_refresh_updated_at
    BEFORE UPDATE ON campaigns
    FOR EACH ROW EXECUTE FUNCTION refresh_updated_at();


CREATE TABLE IF NOT EXISTS events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    name        VARCHAR(150) NOT NULL,
    location    VARCHAR(255),
    start_at    BIGINT,
    end_at      BIGINT,
    created_at  BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    updated_at  BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    is_active   BOOLEAN NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_events_campaign_id ON events(campaign_id);

DROP TRIGGER IF EXISTS events_refresh_updated_at ON events;
CREATE TRIGGER events_refresh_updated_at
    BEFORE UPDATE ON events
    FOR EACH ROW EXECUTE FUNCTION refresh_updated_at();


CREATE TABLE IF NOT EXISTS event_days
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    event_id   BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    day_number INTEGER NOT NULL,
    day_date   BIGINT,
    created_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    updated_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    is_active  BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT ux_event_day UNIQUE (event_id, day_number)
);

CREATE INDEX IF NOT EXISTS idx_event_days_event_id ON event_days(event_id);

DROP TRIGGER IF EXISTS event_days_refresh_updated_at ON event_days;
CREATE TRIGGER event_days_refresh_updated_at
    BEFORE UPDATE ON event_days
    FOR EACH ROW EXECUTE FUNCTION refresh_updated_at();
