CREATE TABLE IF NOT EXISTS blog_post
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         UUID         NOT NULL UNIQUE,
    created_at   BIGINT       NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    updated_at   BIGINT       NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    slug         VARCHAR(200) NOT NULL UNIQUE,
    title        VARCHAR(200) NOT NULL,
    excerpt      TEXT,
    content_md   TEXT         NOT NULL,
    cover_url    TEXT,
--     author_name  VARCHAR(120),
    user_id      BIGINT  NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    search_tsv   tsvector,

    CONSTRAINT fk_blog_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT

);

CREATE TABLE IF NOT EXISTS blog_page
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         UUID         NOT NULL UNIQUE,
    created_at   BIGINT       NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    updated_at   BIGINT       NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    slug         VARCHAR(200) NOT NULL UNIQUE,
    title        VARCHAR(200) NOT NULL,
    content_md   TEXT         NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'DRAFT'
);

CREATE TABLE IF NOT EXISTS blog_tag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL UNIQUE,
    created_at BIGINT       NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    updated_at BIGINT       NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    slug       VARCHAR(120) NOT NULL UNIQUE,
    name       VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS blog_post_tag
(
    post_id BIGINT NOT NULL REFERENCES blog_post (id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES blog_tag (id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE IF NOT EXISTS blog_page_tag
(
    page_id BIGINT NOT NULL REFERENCES blog_page (id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES blog_tag (id) ON DELETE CASCADE,
    PRIMARY KEY (page_id, tag_id)
);


CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_blog_post_updated_at ON blog_post;
CREATE TRIGGER trg_blog_post_updated_at
    BEFORE UPDATE
    ON blog_post
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_blog_page_updated_at ON blog_page;
CREATE TRIGGER trg_blog_page_updated_at
    BEFORE UPDATE
    ON blog_page
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION blog_post_search_tsv_trigger()
    RETURNS trigger AS
$$
BEGIN
    NEW.search_tsv :=
            setweight(to_tsvector('simple', coalesce(NEW.title, '')), 'A') ||
            setweight(to_tsvector('simple', coalesce(NEW.excerpt, '')), 'B') ||
            setweight(to_tsvector('simple', coalesce(NEW.content_md, '')), 'C');
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_blog_post_search_tsv ON blog_post;
CREATE TRIGGER trg_blog_post_search_tsv
    BEFORE INSERT OR UPDATE
    ON blog_post
    FOR EACH ROW
EXECUTE FUNCTION blog_post_search_tsv_trigger();

-- indice
CREATE INDEX IF NOT EXISTS idx_blog_post_search_tsv
    ON blog_post USING GIN (search_tsv);

-- BlogPost indexes
CREATE INDEX IF NOT EXISTS idx_blog_post_status_pub ON blog_post (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_post_pub_at ON blog_post (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_post_slug ON blog_post (slug);
CREATE INDEX IF NOT EXISTS idx_blog_post_status_published_at ON blog_post (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_post_author_name ON blog_post (user_id);
CREATE INDEX IF NOT EXISTS idx_blog_post_tag_post_id ON blog_post_tag (post_id);
CREATE INDEX IF NOT EXISTS idx_blog_post_tag_tag_id ON blog_post_tag (tag_id);
CREATE INDEX IF NOT EXISTS idx_blog_tag_slug ON blog_tag (slug);

-- FTS
CREATE INDEX IF NOT EXISTS idx_blog_post_search_tsv ON blog_post USING GIN (search_tsv);

-- BlogPage indexes
CREATE INDEX IF NOT EXISTS idx_blog_page_status_pub ON blog_page (status, created_at DESC);

-- Tag indexes (slug già unique)
CREATE INDEX IF NOT EXISTS idx_blog_tag_slug ON blog_tag (slug);

-- Join tables
CREATE INDEX IF NOT EXISTS idx_blog_post_tag_tag ON blog_post_tag (tag_id);
CREATE INDEX IF NOT EXISTS idx_blog_post_tag_post ON blog_post_tag (post_id);

CREATE INDEX IF NOT EXISTS idx_blog_page_tag_tag ON blog_page_tag (tag_id);
CREATE INDEX IF NOT EXISTS idx_blog_page_tag_page ON blog_page_tag (page_id);

CREATE EXTENSION IF NOT EXISTS pg_trgm;